require:
  - rubocop-rspec
  - rubocop-performance
  - rubocop-rake
  
AllCops:
    NewCops: enable

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Naming/MethodParameterName:
  Enabled: true
  AllowedNames:
    - x
    - y
    - z
    - _
    - to
    - id
    - x1
    - x2
    - y1
    - y2